version = 1

[[annotations]]
path = ["run", "**/*.*"]
precedence = "closest"
SPDX-FileCopyrightText = "2022-present Cosray developers and contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["panel/icons/*.svg"]
precedence = "override"
SPDX-FileCopyrightText = "2019-2024 The Bootstrap Authors"
SPDX-License-Identifier = "MIT"
