version = 1

[[annotations]]
path = ["run", "**/*.*"]
precedence = "closest"
SPDX-FileCopyrightText = "2022-present Cosray developers and contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "panel/src/components/icons/IcoLink.svelte",
    "panel/src/components/icons/IcoTextHeight.svelte",
    "panel/src/components/icons/IcoUnlink.svelte",
]
precedence = "override"
SPDX-FileCopyrightText = "2023 Fonticons, Inc."
SPDX-License-Identifier = "CC-BY-4.0"
